apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-addiction-deployment
  labels:
    app: mobile-addiction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile-addiction
  template:
    metadata:
      labels:
        app: mobile-addiction
    spec:
      containers:
      - name: mobile-addiction-app
        image: mobile-addiction-eeg:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
