apiVersion: v1
kind: Service
metadata:
  name: mobile-addiction-service
  labels:
    app: mobile-addiction
spec:
  type: NodePort
  selector:
    app: mobile-addiction
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
